#! /bin/bash
# Source function library.
. /etc/init.d/functions

case "$1" in
  start)
	systemctl start xcp-networkd
	;;
  stop)
	systemctl stop xcp-networkd
	;;
  restart)
	systemctl restart xcp-networkd
	;;
  status)
	systemctl status xcp-networkd
	;;
  condrestart)
	[ -f /var/lock/subsys/xcp-networkd ] && systemctl restart xcp-networkd || :
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart}"
	exit 1
esac
