#!/bin/sh
set -e

. /etc/xensource-inventory
XENVM_D=/var/run/nonpersistent/xenvm.d

scratch=$(mktemp -d -t tmp.XXXXXXXXXX)
function finish {
  rm -rf "$scratch"
}
trap finish EXIT

ALL=$(ls -1 $XENVM_D | grep "^VG_" | cut -f 1 -d '.' | sort | uniq)
cd $scratch
for i in $ALL; do
  xenvm host-dump $i $INSTALLATION_UUID
  DEVICE=$(cat $XENVM_D/$i.xenvmd.config | grep devices | sed -r 's/\(devices \((.+)\)\)/\1/g')
  xenvm dump $DEVICE > lvm.meta
done
tar -cj *
