#!/bin/sh
set -e

. /etc/xensource-inventory
XENVM_D=/etc/xenvm.d

scratch=$(mktemp -d -t tmp.XXXXXXXXXX)
function finish {
  rm -rf "$scratch"
}
trap finish EXIT

ALL=$(ls -1 $XENVM_D | grep "^VG_" | cut -f 1 -d '.' | sort | uniq)
cd $scratch
for i in $ALL; do
  xenvm host-dump $i $INSTALLATION_UUID
done
tar -cj *
